# Specific profile to run CentralPerf in a Docker container build with Docker Compose
spring:
  # Spring JDBC configuration
  datasource:
    url: jdbc:postgresql://db:5432/centralperf
    username: centralperf
    password: centralperf
    driver-class-name: org.postgresql.Driver
  elasticsearch:
    rest:
      uris: http://es:9200
centralperf:
  elastic:
    kibana:
      internal-url: http://kibana:5601
jmeter:
  launcher:
    type: docker_container
logging:
  level:
    com.github.dockerjava: debug
    org.centralperf: debug
    org.springframework.web: info