# Specific profile to run CentralPerf in a Docker container build with Docker Compose

server:
  address: centralperf

spring:
  # Spring JDBC configuration
  datasource:
    url: jdbc:postgresql://db:5432/centralperf
    username: centralperf
    password: centralperf
    driver-class-name: org.postgresql.Driver
  elasticsearch:
    rest:
      uris: http://es:9200
  boot:
    admin:
      client:
        enabled: true
        url: http://spring-boot-admin:1111
        instance:
          name: CentralPerf Webapp
        api-path: "boot-admin/instances"

centralperf:
  elastic:
    kibana:
      internal:
        url: http://kibana:5601
        base-path: /kibana
      public-url: /kibana # Relative URL and context of Traefik Reverse Proxy

jmeter:
  launcher:
    type: docker_container

logging:
  level:
    org.centralperf: info
